### ISSUE TITLE
Azata Hero Never Surrender Cause All Spellbooks Added

### ISSUE THREAD

**Issue by ForbAvalon** [vikigenius/SpellbookMerge#16] opened 2022-02-10 14:06 UTC
As title says ,  I used sword saints merged azata mysticbooks , when i use lv7 spell hero never surrender I will get all spellbooks added to my charactor

**Comment by ForbAvalon** [comment] 2022-02-10 14:18
And i test skald and bard will cause this problem.
My game version is 1.1.7f

**Comment by vikigenius** [comment] 2022-02-10 15:49
Duplicate of https://github.com/vikigenius/SpellbookMerge/issues/12

**Closed by vikigenius** 2022-02-10 15:49 UTC
Labels: duplicate
