### ISSUE TITLE
No longer Add caster level with New Update.

### ISSUE THREAD

**Issue by Cairnos** [vikigenius/SpellbookMerge#26] opened 2022-11-26 14:26 UTC
Not Sure which update breaks it, but in 2.0.4k, the merging doesnt add any spell caster level for your merged class.

Even basic merging like cleric+Angel doesnt work anymore.

**Comment by vikigenius** [comment] 2022-11-29 01:15
It would be helpful if you can attach the UMM logs as a pastebin, or even post it here. I don't play the game anymore (don't even have it installed) so can't reproduce the issue reliably

**Comment by Cylush** [comment] 2022-12-04 22:58
Not entirely sure if this is what you're looking for, but here the log files found in the Owlcat > WOTR folder. I had to upload my player.log to Mediafire, as it's 157MB, and every paste site I tried to paste it to crashed or didn't allow it. If you'd prefer a different site, like something with a file checker, let me know your preference and I'll upload to that.
[GameLogFull.txt](https://github.com/vikigenius/SpellbookMerge/files/10149670/GameLogFull.txt)
Player.log - https://www.mediafire.com/file/36zwppmja2da58n/Player.log/file

**Comment by vikigenius** [comment] 2022-12-05 01:04
I mean when you have UMM installed, when the game loads, the UMM window has a button that says something like "check UMM logs" or "open log file". That logfile is what's important, it will describe when every mod loads and all that. An easy way to isolate issues is uninstall other mods so that we can easily isolate what's the issue with this specifically

**Comment by vikigenius** [comment] 2022-12-05 01:06
I just checked, there doesn't seem to be any obvious issue in the code. Owlcat must have changed something internally. You can check the last few recent patch notes and see if they have changed anything re merging and caster level.

**Comment by vikigenius** [comment] 2022-12-05 01:06
Also, Can you provide screenshots of a merged spellbook and it's caster level on your character sheet?

**Comment by Cylush** [comment] 2022-12-05 02:14
Yeah, the UMM log is in the mediafire, though I can re-upload it now that I removed some mods that clog the log up. 
[Player.log](https://github.com/vikigenius/SpellbookMerge/files/10150146/Player.log)
![image](https://user-images.githubusercontent.com/32019955/205534331-acbf7601-1054-49f8-b6a9-f1fce9de6e4c.png)
![image](https://user-images.githubusercontent.com/32019955/205534347-8186dc70-dfa6-460b-b483-a6b598adb353.png)

**Comment by vikigenius** [comment] 2022-12-05 18:41
Ok the issue is apparently with ToyBox. A modder is working on a fix for it. Will be closing this issue.

From the Discord Comment

> Not you. Blame me/toybox. I've got a fix waiting for the next release.

**Closed as completed** 2022-12-05 18:41 UTC
